/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.io.InputStream;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import model.partD.staff.AuthService;
import model.partD.staff.SessionManager;
import model.partD.staff.StaffRegistry;

/**
 *
 * @author Deneth
 */
public class LoginPage extends javax.swing.JFrame {

    private final StaffRegistry staffRegistry = new StaffRegistry();
    private final SessionManager sessionManager = new SessionManager();
    private final AuthService authService = new AuthService(staffRegistry, sessionManager);
    JTextField txtUser;
    JPasswordField txtPass;

    public LoginPage() {
        JFrame frame = new JFrame("Login Page");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 250);
        frame.setLayout(null);

        // Panel (optional, for grouping)
        JPanel panel = new JPanel();
        panel.setLayout(null);
        panel.setBounds(0, 0, 400, 250);
        frame.add(panel);

        // Username Label + Field
        JLabel lblUser = new JLabel("Username:");
        lblUser.setBounds(50, 50, 100, 25);
        panel.add(lblUser);

        txtUser = new JTextField();
        txtUser.setBounds(150, 50, 180, 25);
        panel.add(txtUser);

        // Password Label + Field
        JLabel lblPass = new JLabel("Password:");
        lblPass.setBounds(50, 90, 100, 25);
        panel.add(lblPass);

        txtPass = new JPasswordField();
        txtPass.setBounds(150, 90, 180, 25);
        panel.add(txtPass);

        // Login Button
        JButton btnLogin = new JButton("Login");
        btnLogin.setBounds(150, 130, 80, 30);
        panel.add(btnLogin);

        // Clear Button
        JButton btnClear = new JButton("Clear");
        btnClear.setBounds(250, 130, 80, 30);
        panel.add(btnClear);

        // Result Label
        JLabel lblResult = new JLabel("");
        lblResult.setBounds(50, 170, 300, 25);
        lblResult.setForeground(Color.RED);
        panel.add(lblResult);

        // Login Button Action
        btnLogin.addActionListener(e -> {
//                            showLoginDialog();

//            Object[] message = {
//                "User ID:", txtUser.getText(),
//                "Password:", txtPass.getPassword()
//            };
//
//            int option = JOptionPane.showConfirmDialog(this, message, "Login", JOptionPane.OK_CANCEL_OPTION);
//            if (option == JOptionPane.OK_OPTION) {
            String user = txtUser.getText().trim();
            String pass = new String(txtPass.getPassword());

            boolean ok = authService.login(user, pass);
            if (!ok) {
                JOptionPane.showMessageDialog(this, "Invalid credentials.");
                // try again
            } else {
                JOptionPane.showMessageDialog(this, "Welcome, " + authService.getCurrentUserId() + " (" + authService.getCurrentRole() + ")");
                System.out.println(sessionManager.isLoggedIn());
                System.out.println(sessionManager.currentRole());
                System.out.println(sessionManager.currentUserId());
                // Optionally enable tabs based on role, or just keep permission checks on actions
                HealthcareManagementSystemGUI h = new HealthcareManagementSystemGUI();
                h.setVisible(true);
                this.dispose();
                System.out.println(sessionManager.isLoggedIn());
                System.out.println(sessionManager.currentRole());
                System.out.println(sessionManager.currentUserId());
            }

            frame.dispose();
            // Example validation (replace with DB check)
        });

        // Clear Button Action
        btnClear.addActionListener(e -> {
            txtUser.setText("");
            txtPass.setText("");
            lblResult.setText("");
        });

        frame.setLocationRelativeTo(null); // center screen
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // At top-level of GUI class


        /* Create and display the form */
        try {
            // Set FlatLaf Light theme
            UIManager.setLookAndFeel(new FlatLightLaf());

            // Or set Dark theme
            // UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF: " + ex);
        }

        SwingUtilities.invokeLater(
                () -> {

                    LoginPage frame = new LoginPage();
                    frame.setVisible(true);
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
