/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.io.InputStream;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author Deneth
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        try {
            // Set FlatLaf Light theme
            UIManager.setLookAndFeel(new FlatLightLaf());

            // Or set Dark theme
            // UIManager.setLookAndFeel(new FlatDarkLaf());

        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF: " + ex);
        }

         SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Login Page");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(400, 250);
            frame.setLayout(null);

            // Panel (optional, for grouping)
            JPanel panel = new JPanel();
            panel.setLayout(null);
            panel.setBounds(0, 0, 400, 250);
            frame.add(panel);

            // Username Label + Field
            JLabel lblUser = new JLabel("Username:");
            lblUser.setBounds(50, 50, 100, 25);
            panel.add(lblUser);

            JTextField txtUser = new JTextField();
            txtUser.setBounds(150, 50, 180, 25);
            panel.add(txtUser);

            // Password Label + Field
            JLabel lblPass = new JLabel("Password:");
            lblPass.setBounds(50, 90, 100, 25);
            panel.add(lblPass);

            JPasswordField txtPass = new JPasswordField();
            txtPass.setBounds(150, 90, 180, 25);
            panel.add(txtPass);

            // Login Button
            JButton btnLogin = new JButton("Login");
            btnLogin.setBounds(150, 130, 80, 30);
            panel.add(btnLogin);

            // Clear Button
            JButton btnClear = new JButton("Clear");
            btnClear.setBounds(250, 130, 80, 30);
            panel.add(btnClear);

            // Result Label
            JLabel lblResult = new JLabel("");
            lblResult.setBounds(50, 170, 300, 25);
            lblResult.setForeground(Color.RED);
            panel.add(lblResult);

            // Login Button Action
            btnLogin.addActionListener(e -> {
                String username = txtUser.getText();
                String password = new String(txtPass.getPassword());

                // Example validation (replace with DB check)
                if (username.equals("admin") && password.equals("1234")) {
                    lblResult.setForeground(Color.GREEN);
                    lblResult.setText("Login Successful!");
                    HealthcareManagementSystemGUI hm = new HealthcareManagementSystemGUI();
                    hm.setVisible(true);
                    frame.dispose();
                    JOptionPane.showMessageDialog(frame, "Welcome " + username, "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    lblResult.setForeground(Color.RED);
                    lblResult.setText("Invalid Username or Password!");
                }
            });

            // Clear Button Action
            btnClear.addActionListener(e -> {
                txtUser.setText("");
                txtPass.setText("");
                lblResult.setText("");
            });

            frame.setLocationRelativeTo(null); // center screen
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
